language: php
sudo: false

php:
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4snapshot'

services:
  - docker

before_script:
  - composer update
  - sudo service mysql stop
  - cd $( pwd )/scripts && ./docker-run.sh

script:
  - ./vendor/bin/phpcs --standard=PSR2 -n src
  - ./vendor/bin/psalm
  - ./vendor/bin/phpstan analyse --level 7 src
  - ./vendor/bin/phpunit
