language: php
sudo: false

php:
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4snapshot'

services:
  - mysql

before_script:
  - composer update
  - mysql < ./scripts/schema.sql

script:
  - ./vendor/bin/phpcs --standard=PSR2 -n src
  - ./vendor/bin/psalm
  - ./vendor/bin/phpunit
