language: php
sudo: false

php:
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4'
  - '8.0'

services:
  - mysql

before_script:
  - composer update
  - mysql < ./scripts/schema.sql

script:
  - ./vendor/bin/parallel-lint src
  - ./vendor/bin/phpcs --standard=PSR2 -n src
  - php -v | grep -q 'PHP 7.' || ./vendor/bin/phpunit --testdox
  - php -v | grep -q 'PHP 7.' || ./vendor/bin/psalm
